### ISSUE TITLE
4) 메인 > 카테고리 > 카테고리 오류

### ISSUE THREAD

**Issue by ghkdwls30** [ghkdwls30/Winner#1]
[버그명]
카테고리 이동시 오류나는 버그

[재현방법]

![image](https://user-images.githubusercontent.com/30769351/29993639-e38909dc-8ff7-11e7-8cb1-56336a1096fb.png)

[오류가난뒤]

![image](https://user-images.githubusercontent.com/30769351/29993646-fc5692f4-8ff7-11e7-955d-2d9a02115e91.png)
계속돌아가고있는 모습

**Comment by ghkdwls30** [comment]
xxx

**Comment by siven1** [comment]
메일오나

**Comment by ghkdwls30** [comment]
@siven1  
뉴스 카테고리 이동 후 이미지 카테고리는 사실 이동 불가능하지만
우리의 개발정책은 오류를 사용자의 실수로 오류를 내지 않는 것이기 때문에
카테고리 -> 카테고리는 자동으로 홈으로 이동한 다음에 카테고리를 이동처리하는 것으로 하겠음.

**Comment by siven1** [comment]
@ghkdwls30 오케이

**Comment by ghkdwls30** [comment]
@siven1  
개발완료 테스트 요망
https://drive.google.com/open?id=0B6OI9LRXJ47SaS03QnpQTHhWVzQ
