### ISSUE TITLE
4) 기능추가 (검색어 디비 활용해서 랜덤검색기능) 

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#18]
기능명 : 디비 랜덤검색 기능

설명 : 
1. 디비에 검색할 검색어를 미리 적어둔다.
2. 적어둔 검색어로 랜덤으로 뽑아서 네이버검색창에 검색을 한다.

**Comment by ghkdwls30** [comment]
@siven1  
1. 키워드검색에서 검색어가 없을 경우 키워드 딕셔너리에서 가져다가 검색.
2. 키워드검색에서 검색어가 있으면 그 검색어로 검색함.

**Comment by ghkdwls30** [comment]
@siven1 
컬럼은 어떤것들이 필요할까? 
키워드만 있으면되나?

**Comment by ghkdwls30** [comment]
@siven1 
개발완료
