### ISSUE TITLE
7) 메인에서 게시글조회 오류

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#19]
버그명 : 메인에서 바로 게시글조회 오류  메인 > 게시글

작업재현: 
![image](https://user-images.githubusercontent.com/30769351/29997552-1d212dc4-9051-11e7-8e88-23954b277486.png)
[NaverRelateSearch - 복사본.sqlite.txt](https://github.com/ghkdwls30/Winner/files/1272363/NaverRelateSearch.-.sqlite.txt)

실행후 : 
메인에서 멈춰있다. 첨부파일은 복사본임. 
복사본지우고 txt 지우고 해주셈
@ghkdwls30 오류

**Comment by siven1** [comment]
@ghkdwls30 이게왜자꾸오류인지 모르겟네

**Comment by ghkdwls30** [comment]
@siven1 
해당 기능은 코드에 오류가 있었음.

**Comment by ghkdwls30** [comment]
@siven1  뮤슨오류?
