### ISSUE TITLE
8) 메인에서 하단검색창 검색오류

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#20]
버그명: 메인 > 랜덤하단검색 오류남

작업재현:

![image](https://user-images.githubusercontent.com/30769351/30000981-39802e52-90ba-11e7-9d3b-1e5792a127b2.png)

@ghkdwls30  버그

**Comment by siven1** [comment]
@ghkdwls30 하단이 없으면 상단으로

**Comment by ghkdwls30** [comment]
@siven1 완료
