### ISSUE TITLE
9)게시글 들어가서 카테고리이동 오류

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#21]
버그명: 게시글들어가서 카테고리이동 하면 오류

재현순서:

![image](https://user-images.githubusercontent.com/30769351/30001018-9875ada0-90bb-11e7-9180-a2827162ed3e.png)

버그메세지: 

![image](https://user-images.githubusercontent.com/30769351/30001019-a84bb5da-90bb-11e7-99e0-ded204acf99d.png)

[NaverRelateSearch - 복사본.sqlite.txt](https://github.com/ghkdwls30/Winner/files/1272765/NaverRelateSearch.-.sqlite.txt)

test1 로직으로 돌려보면암

**Comment by siven1** [comment]
@ghkdwls30 이거 예외좀 해주셈.... 홈으로가서 카테고리 이동으로

**Comment by siven1** [comment]
@ghkdwls30 재테스트한걸로봐선 메인에서 카테고리가 없는건 안되는듯 또오류

**Comment by ghkdwls30** [comment]
@siven1  완료
