### ISSUE TITLE
10) 버그 (검색을하고 카테고리를 이동하면 홈으로가서 이동함)

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#24]
버그명 : 검색하고 카테고리이동 버그

작업재현: 
![image](https://user-images.githubusercontent.com/30769351/30113205-de13992c-934e-11e7-8a0b-d513d476694d.png)

검색하고 카테고리이동 하는데  홈으로가서 메인 카테고리로 이동함.

**Comment by siven1** [comment]
@ghkdwls30 버그

**Comment by ghkdwls30** [comment]
@siven1  수정완료

**Comment by ghkdwls30** [comment]
완료

**Comment by siven1** [comment]
와우
