### ISSUE TITLE
1) 메인 > 카테고리(블로그) > 게시글조회 TEST 

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#3]
버그명 :  메인 > 블로그들어가서 게시글조회가 안되고 멈춤현상

재현방법

![test1](https://user-images.githubusercontent.com/30769351/29993499-87d2195c-8ff3-11e7-9c22-11539fd4121c.PNG)

**Comment by ghkdwls30** [comment]
ddd

**Comment by ghkdwls30** [comment]
메일

**Comment by siven1** [comment]
메일

**Comment by siven1** [comment]
mail

**Comment by siven1** [comment]
rrrrrrrrrrrrr

**Comment by ghkdwls30** [comment]
@siven1 완료
