### ISSUE TITLE
2) 메인 > 카페 들어가서 게시글조회가 안되고 멈춤현상

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#6]
버그명 : 메인 > 카페 들어가서 게시글조회가 안되고 멈춤현상

재현방법

![image](https://user-images.githubusercontent.com/30769351/29993609-12771cbc-8ff7-11e7-9f7c-16bdb059203a.png)

**Comment by ghkdwls30** [comment]
@siven1 완료
