### ISSUE TITLE
3) 메인 > 뉴스 들어가서 게시글조회가 안되고 멈춤현상

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#7]
버그명 :  뉴스 들어가서 게시글조회가 안되고 멈춤현상

재현방법 :

![image](https://user-images.githubusercontent.com/30769351/29993618-4cb6eb14-8ff7-11e7-97c8-0a0291c1798f.png)

**Comment by siven1** [comment]
갓황 ㄱ

**Comment by siven1** [comment]
shxlffj89

**Comment by ghkdwls30** [comment]
@siven1  메인에서? 검색창의 뉴스에서?

**Comment by ghkdwls30** [comment]
@siven1  완료
