### ISSUE TITLE
5) 메인 > 카테고리 > 홈으로가기 오류 

### ISSUE THREAD

**Issue by siven1** [ghkdwls30/Winner#8]
버그명 : 메인 > 카테고리 > 홈으로가기 오류 

재현방법 :

![image](https://user-images.githubusercontent.com/30769351/29993729-195a1d4c-8ffa-11e7-8f95-08e24e984100.png)

실행후 :

![image](https://user-images.githubusercontent.com/30769351/29993735-36fd27e0-8ffa-11e7-879d-636234a134c1.png)

창은꺼지면서 계속돌아가고있음.

**Comment by siven1** [comment]
테스트

**Comment by siven1** [comment]
@ghkdwls30 댓글TEST

**Comment by ghkdwls30** [comment]
@siven1  완료
